### ISSUE TITLE
CCL und DCL wird am Display nicht korrekt angezeigt

### ISSUE THREAD

**Issue by lordnibbler22** [shining-man/bsc_display#11]
z.B. wird CCL 150A und DCL 200A eingestellt. Am Display wird 15A und 20A angezeigt.

BSC Firmware: V0.6.1_T8
Display Firmware: 1.0.2

![IMG_3402](https://github.com/user-attachments/assets/783d9f1a-77b2-42ab-bf0a-92394f265006)
![IMG_3401](https://github.com/user-attachments/assets/4def2f7e-c0cd-4cfd-a84f-369287491ce5)

**Comment by tueftler0** [comment]
Bitte letzte Testversion aus dem Discord nutzen. Darin ist dies gefixt

**Comment by tueftler0** [comment]
Bitte letzte Testversion aus dem Discord nutzen. Darin ist dies gefixt

**Comment by tueftler0** [comment]
Doppelpost zu https://github.com/shining-man/bsc_display/issues/2
