### ISSUE TITLE
Daten werden auf dem Display nicht korrekt angezeigt

### ISSUE THREAD

**Issue by RRonGit** [shining-man/bsc_display#2]
**Umgebung:**

BSC Hardware 2.5 und Firmware v0.6.0
Display: WT32-SC01 V3.3

Der BSC liest zwei Seplos Akkus aus. Seplos BMS V16 (10E) Software Version: 16.6

Im Webgui des BSC werden die Daten korrekt angezeigt.

Auf dem Display wie folgt:

### Home:
Wechselrichter Lade. Entl. Strom stimmt um den Faktor 10 nicht
(hier gibt es schon einen Pull request von tueftler0 https://github.com/shining-man/bsc_display/pull/1)

![BSCD_Screen_1](https://github.com/shining-man/bsc_display/assets/11077414/15cc969c-1cfd-419d-ba9d-f57a22cddd6a)

**BMS:**

es sind zwei Seplos Akkus an Serial 2 u. 3 angeschlossen
müssten hier die Werte nicht in der Spalte 2 und 3 auftauchen?

![BSCD_Screen_2](https://github.com/shining-man/bsc_display/assets/11077414/30a272a7-3ec3-432e-82c8-5e5f919591df)

**Cell Spg.:**
müssten die Zellspannungen nicht in der Spalte 2 und 3 stehen?

![BSCD_Screen_3](https://github.com/shining-man/bsc_display/assets/11077414/0df679a4-7050-4874-bc5c-0b51a1cbff7f)

**Info:**
soweit i.O.

![BSCD_Screen_4](https://github.com/shining-man/bsc_display/assets/11077414/93b0d192-4c15-484a-a345-afbbb67b4a0c)

**Comment by shining-man** [comment]
Das mit den Spannungen past so. Die ersten 5 Spalten sind die BT-Geräte (Mehr als 5 gingen am Anfang nicht). 
Sie Spalten 5-7 entsprechen Serial 0-2. Am Anfang gab es nur drei Serials.
Die Anzeige gehört etwas überarbeitet. Evtl. geteilt in zwei Screens. BT und Serials.

**Comment by RRonGit** [comment]
@shining-man Ok, danke für deine Infos.

**Comment by 21-Jailbraik-21** [comment]
Darf man fragen, welches Display ( link ) es ist - suche auch das 3.3 ?


Danke Dir

**Comment by RRonGit** [comment]
@21-Jailbraik-21 ich habe dieses hier gekauft und bekam dann die Version 3.3 geliefert:
https://de.aliexpress.com/item/1005003191471709.html?spm=a2g0o.order_list.order_list_main.4.58415c5fD8bp2A&gatewayAdapt=glo2deu

**Comment by tueftler0** [comment]
Display-Bild von v3.3 in Wiki eingefügt für den Kauf:
https://github.com/shining-man/bsc_fw/wiki/02-Hardware#display-nutzung

**Comment by 21-Jailbraik-21** [comment]
Mion, ist das nun gefixt, wie im Discord zu lesen? 
Habe heute neu geflasht ( erste mal) und habe den gleichen bug.

Danke und netten Tag.

**Comment by RRonGit** [comment]
Wäre es allenfalls möglich, dass auf dem Display nur die im BSC konfigurierten BMSen angezeigt werden?
Wäre so vermutlich etwas übersichtlicher.

**Comment by RRonGit** [comment]
@tueftler0 

> Könnte man machen, ja. Ist aber schon ein Aufwand. Sei so nett und mach dazu einen neuen Issue auf. Danke.

der Issue ist erstellt --> https://github.com/shining-man/bsc_display/issues/8

**Comment by tueftler0** [comment]
@shining-man  Issue kann meines Erachtens geschlossen werden.
