### ISSUE TITLE
v1.0.2 beta Relais Reihenfolge

### ISSUE THREAD

**Issue by Vitalic66** [shining-man/bsc_display#9]
Die Zuordnung scheint nicht korrekt zu sein.

Wenn im BSC das Relais 1 getriggert wird, leuchtet im Display Relais 5 (6).

Im zuge dessen, wäre es vielleicht auch sinnvoll die Beschriftungen anzupassen.

Auf der BSC Paltine werden die Relais 1 bis 6 genannt, im Display 0 bis 5. Im BSC selbst steht wiederum Relaisausgang 0 bis 5.

**Comment by tueftler0** [comment]
In nächster Beta enthalten

**Comment by tueftler0** [comment]
@Vitalic66 Problem ist behoben, bitte schliessen. Danke
